### ISSUE TITLE
NME project wont compile in HaxeDevelop

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-templates#3]
Compiling project throws
Error: You must have a "project.nmml" file or specify another valid project file when using the 'build' command

## Possible Solution
Project->Properties change Compile Target->Custom to Application and add project.nmml to Output file: field

**Comment by ianharrigan** [comment]
Works fine for me:

![image](https://cloud.githubusercontent.com/assets/3024242/19707410/b8ae274a-9b17-11e6-9e22-6c37c7a3b1fe.png)

**Comment by ianharrigan** [comment]
That said, your change has no effect on my system / setup... so ill add it to the templates... it seems more consistent with what openfl does

**Comment by ianharrigan** [comment]
Can you reinstall the .fdz and see if that works out the box?

Cheers,
Ian

**Comment by hoseyjoe** [comment]
It was in universal project f that makes a difference...sorry for not mentiong
